### ISSUE TITLE
Custom key?

### ISSUE THREAD

**Issue by countnazgul** [MiguelSavignano/node-credentials#3]
Although I probably know the answer but still need to ask :)

Is it possible to use custom defined key string? At the moment the key should be 33 characters long (technically i can specify my own 33 characters string). But i was thinking for something more memorable. The case is: at work im having the `.json.key` file locally (and not committing it) and when i return home i want to continue to work on the same project by specifying the key as env variable. But in this case 33 characters might be a bit hard to remember :)

Thanks!

**Comment by MiguelSavignano** [comment]
Hi I try to encrypt the credentials.json with a key with more than 32 characters or less than 32 characters, and Crypto thow this error:

```
internal/crypto/cipher.js:92
    this[kHandle].initiv(cipher, credential, iv, authTagLength);

Error: Invalid key length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:92:19)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:124:20)
    at new Cipheriv (internal/crypto/cipher.js:235:22)
    at Object.createCipheriv (crypto.js:111:10)
```

This mean Crypto need a strong key.

You can decrypt (edit) and change the key (file or ENV) with exact 32 characters and write something memorable like this

```
MY_PASSWORD*********************
```

When I test this I realised that if the key it's incorrect the credentials.json if delete although it has failed de encrypt.

I fixed in v0.1.4
